version: '3.3'
  
services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: iourmwtf

   wordpress:
     depends_on:
       - db
     image: wordpress:fpm
     restart: always
     environment: 
       WORDPRESS_DB_HOST: db:3306 
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: iourmwtf
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./wordpress:/var/www/html
       - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
   nginx:
     image: nginx
     depends_on:
       - wordpress
     ports:
       - 80:80
       - 443:443
     restart: always
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./wordpress:/var/www/html
       - ./logs:/var/log/nginx
       - ./yours.pem:/etc/ssl/ssl.pem
       - ./yours.key:/etc/ssl/ssl.key
